### ISSUE TITLE
Support for compositing of threshold values via `ensemble`

### ISSUE THREAD

**Issue by Martin-Jung** [iiasa/ibis.iSDM#84]
Currently the `threshold()` the exact values `x$get_thresholdvalue()` are created for the provided suitability layer / threshold. But this information is never passed on to any eventual `ensemble()` calls. This can be suboptimal if a threshold is already created by maximizing for example a TSS score with independent data, but then again validated using the same dataset. 

Ideally `ensemble()` should detect and reuse created threshold values if found in a model (or as attribute in a SpatRaster file). This could be supported directly within ensemble by basically using the various threshold values and averaging them as well (so for example a weighted mean of a series of thresholds from the provided models.

**Todo:**
- [x] Add respective parameter to `ensemble()` to reuse threshold values if found (default: true) and apply the same method used for ensemble calculations
- [x] Ensure that there is no logical fallacy when using the same parameter in ensemble forcasts (e.g. applied to scenario objects).
- [x] Add a small unit test to ensure this is tested and works
